name: ESPFlasher Web
version: "1.0.3"
slug: espflasher_web
description: Web-based interface to configure, compile, and flash ESP32 devices via OTA or USB (Web Serial). If there are some Issues with this app or you want to give a Feedback so dont be shy contact me on l.fink@lfdev.de
url: https://github.com/AIRGAMERx/ESPFlasherHAAddOn
arch:
  - aarch64
  - amd64
  - armv7
  - i386

startup: application
boot: auto


ingress: false
webui: "http://[HOST]:[PORT:8099]"


ports:
  8099/tcp: 8099


apparmor: true

options: {}
schema: {}
